### PR TITLE
feat(dashboards): show info tooltip to indicator

### PR DESCRIPTION
**Pull request by ecarreras**
This pull request includes several changes to the `Dashboard` component and its related files to add a description tooltip to the dashboard titles. The most important changes include importing new components and icons, modifying the `Dashboard` function to include descriptions, and updating the `GraphCard` title type.

Enhancements to the `Dashboard` component:

* [`src/widgets/views/Dashboard/Dashboard.tsx`](diffhunk://#diff-41b2831f786fc9fd743234329bcc416218791cd3793374588f995ca91e0c3659L19-R20): Imported `InfoCircleOutlined` from `@ant-design/icons` and `Tooltip` from `antd` to support the new description tooltip feature.
* [`src/widgets/views/Dashboard/Dashboard.tsx`](diffhunk://#diff-41b2831f786fc9fd743234329bcc416218791cd3793374588f995ca91e0c3659R259): Added the `description` property to the `Dashboard` function and implemented the `titleWithTooltip` variable to display the tooltip when a description is present. [[1]](diffhunk://#diff-41b2831f786fc9fd743234329bcc416218791cd3793374588f995ca91e0c3659R259) [[2]](diffhunk://#diff-41b2831f786fc9fd743234329bcc416218791cd3793374588f995ca91e0c3659R390-R404)

Updates to the helper functions:

* [`src/widgets/views/Dashboard/dashboardHelper.ts`](diffhunk://#diff-b000310d538d1185354dc25b6383ef47d94fe792762798480854cc04a5379885R36): Included the `description` property in the `fetchAction` function to pass the description data. [[1]](diffhunk://#diff-b000310d538d1185354dc25b6383ef47d94fe792762798480854cc04a5379885R36) [[2]](diffhunk://#diff-b000310d538d1185354dc25b6383ef47d94fe792762798480854cc04a5379885R75)

Type adjustments:

* [`src/widgets/views/Graph/GraphCard.types.ts`](diffhunk://#diff-3aceecadd26349dc8f5e65b6c1345ef5a5ee80a1cf103c81bdcb7cc6cf19f01aL4-R4): Changed the `title` type from `string` to `any` in `GraphCardProps` to accommodate the new tooltip feature.

image

## Relacionado

- https://github.com/gisce/erp/pull/22734

### CODE REVIEW

**Review by mguellsegarra — APPROVED** [review]

**Comment by ecarreras** [comment]
@mguellsegarra he afegit també el tooltip en els cards del form

**Comment by ecarreras** [comment]
@mguellsegarra estava pensant que potser té més sentit si al `<GraphCard />` li podem passar l'atribut `info` o `description` i que ja ho faci aquest i no tenir el codi duplicat, què et sembla?

**Comment by mguellsegarra** [comment]
> @mguellsegarra estava pensant que potser té més sentit si al `<GraphCard />` li podem passar l'atribut `info` o `description` i que ja ho faci aquest i no tenir el codi duplicat, què et sembla?

Sí, té tot el sentit del món. Vols que ho adapti jo en un moment? :)

**Comment by ecarreras** [comment]
> Sí, té tot el sentit del món. Vols que ho adapti jo en un moment? :)

Genial! 🙌🏻

**Comment by mguellsegarra** [comment]
Fet! Ho he provat, tant pels dashboards i pels indicadors al form, a `ovlab` :)

CleanShot 2024-12-18 at 15 12 25
CleanShot 2024-12-18 at 15 14 45

**Pull request merged**
